package com.mad.assignment3.Models;

import com.google.firebase.auth.FirebaseUser;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is used as a base for each household. This mirrors what is available to view on the Firebase Console.
 */
public class Household {

    private String mName;
    private ArrayList<User> mUsers;
    private List<Item> mShoppingList;
    private String mFirebaseKey;

    /**
     * This constructor is used to generate a household for the first time.
     * By only using a name, a household can be made and the other fields populated later.
     *
     * @param name this becomes the name of the household
     */
    public Household(String name) {
        this.mName = name;
    }

    /**
     * This constructor is used when creating a household object using data from Firebase.
     *
     * @param name the name of the household
     * @param users a list of all users that belong to the household
     * @param items a list of items that are contained within the shopping list
     * @param firebaseKey the unique key generated by the .push() function from Firebase
     */
    public Household(String name, ArrayList<User> users, ArrayList<Item> items, String firebaseKey) {
        this.mName = name;
        this.mUsers = users;
        this.mShoppingList = items;
        this.mFirebaseKey = firebaseKey;
    }

    public Household(){}

    /**
     * This constructor is used prior to the object being pushed to the Firebase Database
     * The missing field, mFirebaseKey, is generated when pushing to the database
     *
     * @param householdName this is the household name
     * @param users this is a list of users that belong to this household
     * @param items this is a list of items on the shopping list
     */
    public Household(String householdName, ArrayList<User> users, ArrayList<Item> items) {
        this.mName = householdName;
        this.mUsers = users;
        this.mShoppingList = items;
    }

    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }

    public ArrayList<User> getUsers() {
        return mUsers;
    }

    public void setUsers(ArrayList<User> users) {
        mUsers = users;
    }

    public List<Item> getShoppingList() {
        return mShoppingList;
    }

    public void setShoppingList(List<Item> shoppingList) {
        mShoppingList = shoppingList;
    }

    public void addUser(User user){
        mUsers.add(user);
    }


    public String getFirebaseKey() {
        return mFirebaseKey;
    }

    public void setFirebaseKey(String firebaseKey) {
        mFirebaseKey = firebaseKey;
    }
}
